### ISSUE TITLE
关于youtube去广告

### ISSUE THREAD

**Issue by shadoway11** [Infatuation-Fei/rule#1]
用stash可以实现全节点Youtube去广告，但是用quanx只有送中节点才能去youtube广告
Stash脚本是用的大佬你的，quanx是用的神机的，大佬可以考虑写一个quanx的YouTube去广告吗

**Comment by Infatuation-Fei** [comment]
我QuantumultX上也是装着神机的YouTube去广告，能去啊，https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Rewrite/Block/YouTubeAds.conf   就是这个，重写引用的
还有，送中节点是根本就没有广告，不用去😂

**Comment by shadoway11** [comment]
啊这……我人傻了，那我找找原因，谢谢大佬

**Comment by Infatuation-Fei** [comment]
怪了，我这边QuantumultX也去不了了🌚昨晚上试还能去，今天试了下就不行了，在Stash正常能去，在QuantumultX上去不了，测试了小火箭也是正常能去，三个软件都是用的一模一样的重写规则，感觉像是QuantumultX问题

**Comment by shadoway11** [comment]
我试了试把分流里的youtube规则关了，现在quanx可以去了……不过要打开两遍youtube，第一遍去不了，然后重新打开一次就行了……
还有忘了说了，我的YouTube是最新的正式版17.10.2，quanx是最新正式版1.0.27

**Comment by ghost** [comment]
> 我试了试把分流里的youtube规则关了，现在quanx可以去了……不过要打开两遍youtube，第一遍去不了，然后重新打开一次就行了……
> 
> 还有忘了说了，我的YouTube是最新的正式版17.10.2，quanx是最新正式版1.0.27

我用的是同样的重新规则，YouTube也是最新版17.10.2，但是去不了广告

**Comment by dysf888** [comment]
> 怪了，我这边QuantumultX也去不了了🌚昨晚上试还能去，今天试了下就不行了，在Stash正常能去，在QuantumultX上去不了，测试了小火箭也是正常能去，三个软件都是用的一模一样的重写规则，感觉像是QuantumultX问题

建议在小火箭油管广告模块加一个说明 把youtube规则删掉才能生效 ,我也不知道是不是这样,反正我把配置里的youtube规则删除了,再添加模块就可以了过滤了
