### ISSUE TITLE
使用mac os x 上的clash 吗

### ISSUE THREAD

**Issue by 78wee** [Infatuation-Fei/rule#10]
请问 这懒人包适合iMac上的clash x使用吗

clash x版本号Version: 1.91.1 (1.91.1)

**Comment by Infatuation-Fei** [comment]
用ClashXPro或者Clash For Windows(有Mac版)，配置模板是适用于Premium内核

ClashX是foss内核，不支持provider，我的配置全是用的provider

**Comment by 78wee** [comment]
哦哦


原来如此瞬间悟了


多谢大佬答复



Yours，
Frank



------------------ 原始邮件 ------------------
发件人: FEI ***@***.***&gt;
发送时间: 2022年4月17日 23:12
收件人: Infatuation-Fei/rule ***@***.***&gt;
抄送: 78wee ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Infatuation-Fei/rule] 使用mac os x 上的clash 吗 (Issue #10)





 
用ClashXPro或者Clash For Windows(有Mac版)，配置模板是适用于Premium内核
 
ClashX是foss内核，不支持provider，我的配置全是用的provider
