### ISSUE TITLE
导入RAW格式的stoverride进入覆写，系统提示“糟糕，格式不正确””

### ISSUE THREAD

**Issue by JackeyLovez** [Infatuation-Fei/rule#13]
我确信我导入的是raw格式的，例如https://raw.githubusercontent.com/Infatuation-Fei/rule/main/Stash/Rule/ADRulesLite.stoverride；

**Comment by Infatuation-Fei** [comment]
你这链接最后多了个分号；

还有导入的时候要开启代理，raw链接是被墙的，不开代理下载不到内容
