### ISSUE TITLE
网易云的复写用不了

### ISSUE THREAD

**Issue by yorunning** [Infatuation-Fei/rule#15]
导入选中后，stash频繁开启关闭、开启关闭，导致stash不能正常用了，不勾选stash才能用，其它的复写都生效没问题。我在想是不是stash复写不支持写代理

**Comment by Infatuation-Fei** [comment]
Override文件夹里的覆写均需要Stash 1.6.0 build263版本及以上才支持，低于这个版本的覆写还不支持覆写添加配置所有内容，可以看看你的Stash版本，你应该用的正式版，还没更新到这个版本

263+版本就支持覆写添加配置里的所有片段了，虽然更新日志及UI上还没有体现，但是支持了，群里客服说了，我这边测试也确实是可以了

**Comment by yorunning** [comment]
> Override文件夹里的覆写均需要Stash 1.6.0 build263版本及以上才支持，低于这个版本的覆写还不支持覆写添加配置所有内容，可以看看你的Stash版本，你应该用的正式版，还没更新到这个版本
> 
> 
> 
> 263+版本就支持覆写添加配置里的所有片段了，虽然更新日志及UI上还没有体现，但是支持了，群里客服说了，我这边测试也确实是可以了

对，我现在在用的是正式版，导入的复习发现只有脚本有用。看来要等更新了，感谢解答。
