### ISSUE TITLE
Stash 覆写中引用外部资源更新间隔问题

### ISSUE THREAD

**Issue by akira304moto** [Infatuation-Fei/rule#17]
您创建的覆写中引用了许多 js 脚本（或外部策略组），interval 大部分均设为 3600（甚至 [Netflix_ratings.stoverride](https://github.com/Infatuation-Fei/rule/blob/main/Stash/Script/Netflix_ratings.stoverride) 中有一个为360），但我追踪发现这些脚本中许多已超过几个月没有更新，若每小时将他们强制后台更新一次，或许会增加不必要的资源占用及耗电。

因此建议考虑更改为 interval 为 86400 或更长。若用户认为脚本需要立即更新，自行点击“远程资源”操作即可。谢谢！

**Comment by Infatuation-Fei** [comment]
已修改，感谢反馈

**Comment by akira304moto** [comment]
非常感谢大佬！
