### ISSUE TITLE
腆着b脸要个小火箭的配置

### ISSUE THREAD

**Issue by shadoway11** [Infatuation-Fei/rule#2]
大佬好，刚买了个小火箭想试试，找了一圈规则发现基本都好久没维护了，所以想求一份小火箭的配置，不知道方便吗

**Comment by Infatuation-Fei** [comment]
小火箭还需要啥配置啊，能直接用Clash配置，至于重写规则再单独去找就行了

**Comment by shadoway11** [comment]
原来如此，竟然可以直接用clash，谢谢大佬
