### ISSUE TITLE
请问能否加一个参数让模块可以小火箭跟surge通用。

### ISSUE THREAD

**Issue by kang000feng** [Infatuation-Fei/rule#21]
尊敬的作者好，感谢您分享模块。关于https://raw.githubusercontent.com/Infatuation-Fei/rule/main/Shadowrocket/Module/YouTubeAds.sgmodule
请问能否加一个参数 %APPEND% 让模块可以小火箭跟surge通用？ 同时启用多个模块 缺少这个参数的话surge会覆盖他前面的的所有主机名, 
谢谢您

hostname = %APPEND% -redirector*.googlevideo.com,*.googlevideo.com,www.youtube.com,s.youtube.com,youtubei.googleapis.com

**Comment by Infatuation-Fei** [comment]
直接去找surge的用就行了，就是神机规则的
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Module/Block/YouTubeAds.sgmodule

我那个Shadowrocket库里放的模块仅仅是我之前自己测试规则用的😂，不建议使用
