### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by liupet** [Infatuation-Fei/rule#23]
大佬求教，怎么配置clashforAndroid，文件导入显示失败

**Comment by Infatuation-Fei** [comment]
用的哪个配置？
CFA必须要先把配置内容修改好后再导入，只有配置无误的情况下才会成功导入。
下载yaml文件，修改内容，本地导入

**Comment by liupet** [comment]
> 



> 
用的Config for Clash.yaml这个，复制的代码

**Comment by Infatuation-Fei** [comment]
按照我上面说的就行了，还有就是注意复制出来的缩进对齐，也没必要复制，直接拿raw链接用下载器下载

**Comment by liupet** [comment]
raw下载，有点问题，我重新看看配置

**Comment by liupet** [comment]
![Screenshot_2023-01-31-02-02-12-318_com github kr3](https://user-images.githubusercontent.com/100564521/215558478-18a8fa07-c521-4fe1-b8fa-478dae327cdc.jpg)

**Comment by Infatuation-Fei** [comment]
你这是URL导入？没看到我前面说的吗，先把文件下载下来(IDM,ADM之类的下载器，用raw链接下载)，然后编辑文件，修改好内容，再通过文件导入
![Screenshot_20230131_101348](https://user-images.githubusercontent.com/58471624/215642936-e33aa8d4-82cf-4a2d-9daa-576b0bc9915b.jpg)

**Comment by liupet** [comment]
那个，我原先是用文件导入的，文件内容需要改什么，我没看到要改什么内容，如果是订阅链接，我没找到可以买的机场....就直接导入的文件内容....
![Screenshot_2023-02-01-19-01-16-998_com.estrongs.android.pop.jpg](https://user-images.githubusercontent.com/100564521/216025236-019fd2d0-f9a2-4f8c-a3db-605f45347537.jpg)
手机上操作太难受了...

**Comment by Infatuation-Fei** [comment]
没有订阅链接那你哪来的节点呢，我这里仅提供配置不提供节点
