### ISSUE TITLE
重写去广告中的两条规则导致百度网盘Mac版显示登录失败，无法进入主界面

### ISSUE THREAD

**Issue by akira304moto** [Infatuation-Fei/rule#24]
如图：
<img width="1212" alt="截屏2023-01-31 08 12 55" src="https://user-images.githubusercontent.com/22417867/215625768-4c9d2695-8c40-44af-b18a-4ee5ddb9b823.png">

排查发现是这两条规则：
    - ^https?:\/\/pan\.baidu\.com\/act\/api\/activityentry - reject
    - ^https?:\/\/pan\.baidu\.com\/rest\/\d\.\d\/pcs\/adx - reject

**Comment by Infatuation-Fei** [comment]
这个规则集是给iOS用的，你排查到问题的话自己修改后用在Mac上就行

**Comment by akira304moto** [comment]
明白，谢谢！
