### ISSUE TITLE
TikTok解锁模块疑似失效

### ISSUE THREAD

**Issue by yamasaki6666** [Infatuation-Fei/rule#25]
还在持续测试中，稍后给出测试全过程

**Comment by yamasaki6666** [comment]
测试设备为iPhone11，插国内电话卡
然后用Stash的大大的解锁模块，打开了复写和MITM等(步骤确定正确)，进入Tiktok 21.1版本，无法刷出来视频
改用Quan X的解锁模块，同样一个IPA，完成设置可以刷出来视频。
但是很邪门，日本Stash解锁模块可用，美国不行？？

**Comment by Infatuation-Fei** [comment]
修改了一下规则，请更新覆写后试试。
我这边测试是可以用了
