### ISSUE TITLE
微博国际版

### ISSUE THREAD

**Issue by XueTeng2** [Infatuation-Fei/rule#4]
安装微博微信去广告脚本之后，微博国际版仍然有开屏广告

**Comment by Infatuation-Fei** [comment]
去的本身就是应用内广告，不是开屏广告，而且国际版好像没啥作用

**Comment by XueTeng2** [comment]
我实测微博国际版时间线中的广告没有了

**Comment by Infatuation-Fei** [comment]
那或许是有点用吧，我也没具体测试过，反正脚本本身就没有去开屏广告就是了😂

**Comment by Infatuation-Fei** [comment]
这个覆写我都没有用，我现在也不用微博，微信公众号里的广告用一般的重写去广告就能去掉

**Comment by XueTeng2** [comment]
已经很不错了，感谢大佬
