### ISSUE TITLE
Spotify解锁

### ISSUE THREAD

**Issue by XueTeng2** [Infatuation-Fei/rule#6]
name: Spotify(iOS15)
desc: 部分解锁premium,建议重新登录,音质不能设置为超高

http:
  mitm:
    - "spclient.wg.spotify.com"
  script:
    - match: ^https?:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)
      name: kuwoD
      type: response
      require-body: true
      timeout: 10
      
script-providers:
  kuwoD:
    url: https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js
    interval: 3600

**Comment by XueTeng2** [comment]
大佬，我参照https://github.com/app2smile/rules，在你的酷我解锁脚本基础上尝试修改成Stash可用的Spotify解锁脚本，但是实测并无解锁作用，希望大佬可以指出问题所在，对我这个小白不吝赐教。

**Comment by Infatuation-Fei** [comment]
因为需要脚本做支持，他没有支持Stash所有就不支持，你看我Script文件夹下有个“不可用”文件夹，里面我就写了Spotify的，不能用

**Comment by XueTeng2** [comment]
明白了，谢谢大佬！
