### ISSUE TITLE
请问Clash的规则ClashX是不是不能用？

### ISSUE THREAD

**Issue by joescon** [Infatuation-Fei/rule#7]
macOS，使用 ClashX的
根据Clash的规则替换掉订阅链接后使用，提示：unsupported type rule set。具体如图

![image](https://user-images.githubusercontent.com/62278481/162565186-ce94a093-5141-4a69-b24b-8736d1a48518.png)

请问是否正常？
如果Clash的版本Clash X不能用，能否出一个Clash X的版本？
感谢！

**Comment by Infatuation-Fei** [comment]
用ClashX Pro或者Clash for Windows(有Mac版)，这俩都是Premium内核

我的配置都是用了provider，用Clash Premium内核才行，ClashX是foss内核不支持provider，只能单写节点、规则，即便是做个foss内核的配置，你的节点也只能一个一个往里放，不能使用provider订阅节点，相当麻烦

**Comment by joescon** [comment]
> 用ClashX Pro或者Clash for Windows(有Mac版)，这俩都是Premium内核
> 
> 我的配置都是用了provider，用Clash Premium内核才行，ClashX是foss内核不支持provider，只能单写节点、规则，即便是做个foss内核的配置，你的节点也只能一个一个往里放，不能使用provider订阅节点，相当麻烦

感谢回复！
已经换成使用 ClashX Pro，可以正常使用。

另外Tiktok能不能类似Netflix一样加进去？现在TikTok是某些节点无法用（例如香港），如果能自定义最好

**Comment by Infatuation-Fei** [comment]
你可以自己照着改，模板我不会随便改动，放个tiktok的rule-provider+rules和策略组就行了。

而且香港节点在手机tiktok上好像能用，只是网页版不行吧

**Comment by joescon** [comment]
> 你可以自己照着改，模板我不会随便改动，放个tiktok的rule-provider+rules和策略组就行了。
> 
> 而且香港节点在手机tiktok上好像能用，只是网页版不行吧

好的。
请问是修改proxy-groups 和 rules，rule providers 三部分就可以？
rule providers 好像没现成的，是要自己写一个？

**Comment by Infatuation-Fei** [comment]
规则集怎么会没有现成的呢，https://github.com/blackmatrix7/ios_rule_script/tree/master/rule 这里基本啥都有。

记得给raw链接前放上这个https://ghproxy.com/ cdn加速，raw链接被墙了，Clash官方内核下载provider不走代理，直接用raw链接下载不下来。

这个链接直接放在raw链接前面就行，就像https://ghproxy.com/https://raw.githubusercontent.com/.......

**Comment by joescon** [comment]
> 规则集怎么会没有现成的呢，https://github.com/blackmatrix7/ios_rule_script/tree/master/rule 这里基本啥都有。
> 
> 记得给raw链接前放上这个https://ghproxy.com/ cdn加速，raw链接被墙了，Clash官方内核下载provider不走代理，直接用raw链接下载不下来。
> 
> 这个链接直接放在raw链接前面就行，就像https://ghproxy.com/https://raw.githubusercontent.com/.......

再次感谢那么详细而且有耐心的说明
我去试试
