### ISSUE TITLE
知乎评价区的广告没过滤掉

### ISSUE THREAD

**Issue by luke-zhang580** [Infatuation-Fei/rule#8]
使用的是statsh, 开启了覆写规则，证书已经安装和信任，mitm 和重写已经打开。
![IMG_275A873B6F95-1](https://user-images.githubusercontent.com/45325652/162573973-b2cbc999-01f1-4a92-9703-0923be29e0d4.jpeg)

**Comment by Infatuation-Fei** [comment]
更新了覆写规则，再去试试吧，我这边测试能去了

**Comment by luke-zhang580** [comment]
我刚刚试了下，广告还是存在，我删除并重新安装了知乎，广告也还在，是不支持最新的8.13.0 吗。
![IMG_C1459CCF8EFB-1](https://user-images.githubusercontent.com/45325652/162575652-9862ddd0-2aa3-4ac4-9d0f-510e32c82476.jpeg)

**Comment by Infatuation-Fei** [comment]
![78A17BED-A965-4B61-B9E2-2B91944C8214](https://user-images.githubusercontent.com/58471624/162576214-9d6cd8ee-bbfb-4bec-a3e4-e984dc7a0582.jpeg)
覆写说明上支持的版本写的多么清楚😅

抓包装8.3.0吧，https://github.com/Infatuation-Fei/rule/tree/main/Stash 这里底部有抓包工具和教程
